stages:
  - test
  - lint


unit_tests:
  stage: test
  script:
    - python --version
    - pip install -r requirements.txt
    - python -m pytest tests/ -v


lint:
  stage: lint
  script:
    - flake8 app/ tests/ --max-line-length=100 --count --statistics



