name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v5.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/mortgage-calculator
          git pull origin main
          docker build -t mortgage-calculator .
          docker stop mortgage-app || true
          docker rm mortgage-app || true
          docker run -d --name mortgage-app -p 8080:8080 mortgage-calculator