name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/ -v

    - name: Run linter
      run: |
        pip install flake8
        flake8 app/ tests/ --max-line-length=100 --count --statistics

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t mortgage-calculator:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag mortgage-calculator:latest ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Останавливаем и удаляем старый контейнер
          docker stop mortgage-calculator || true
          docker rm mortgage-calculator || true
          
          # Pull новой версии образа
          docker pull ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:latest
          
          # Запускаем новый контейнер
          docker run -d \
            --name mortgage-calculator \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/mortgage-calculator:latest
          
          # Очистка старых образов
          docker image prune -f



